program: train.py
method: grid
metric:
 goal: minimize
 name: per_sample_val_loss
parameters:
 limb_width:
  values: [1, 2, 3, 4, 5]
 sigma:
  values: [2, 3, 4, 5]
 img_size:
  values: [224, 336, 386, 448] 
 rotation: 
  values: [0, 1]
 
 
 
